select RAND(543433)
select RAND(543433)
SELECT RAND(100), RAND(), RAND()

-- example of RAND(), produces four different random numbers that are generated by the RAND function
DECLARE @counter SMALLINT;  
SET @counter = 1;  
WHILE @counter < 5  
   BEGIN  
      SELECT RAND() Random_Number  
      SET @counter = @counter + 1  
   END;  
GO
----------------------
drop table tblTestRand;

create table tblTestRand(id int, first_name varchar(25), last_name varchar(25))

select * from tblTestRand;

-- error: String or binary data would be truncated.
/*
SET ANSI_WARNINGS  OFF;
-- Your insert TSQL here.
SET ANSI_WARNINGS ON;
*/
SET ANSI_WARNINGS OFF;
insert into tblTestRand(id, first_name, last_name)
values(1, 'john', 'abbott');
insert into tblTestRand
values(2, 'david', 'johnson'),(3,'Tom','jerry'),(4,'Jason','San Antonio'),(5,'William','New York'),
(6,'Donna','San Jose'),
(7,'Michelle','Boston');

select * from tblTestRand
order by first_name;

-- newid() to list the rows in a random order
select * from tblTestRand
order by newid();

DECLARE @NmbrPeople INT  
SELECT @NmbrPeople = COUNT(*)  
FROM tblTestRand;  
PRINT 'The number of people as of ' +  
      CAST(GETDATE() AS CHAR(20)) + ' is ' +  
      CAST(@NmbrPeople AS CHAR(10));  
select  CAST(@NmbrPeople AS CHAR(10));
GO

/* ORDER BY 
oracle:      DBMS_RANDOM.VALUE
SQL server:  NEWID()
PostgreSQL:  random()
MySQL:		 rand()
*/