------ copy only the schema to a new table, without any data -----
SELECT * INTO newtable
FROM OrderDetails
WHERE 1 = 0;
select * from newtable;

-- select into with JOIN --
select ...
into newTable
from ...
join ...
on ...